version: '3.8'

services:
  nextengine-app:
    # A imagem deve ser construída localmente. Ex: docker build -t nextengine:1.1 .
    image: nextengine:1.1 # Mantenha a versão da sua imagem aqui
    networks:
      # Conecta o serviço à rede externa do Traefik
      - network_public # IMPORTANTE: Verifique se este é o nome correto da sua rede Traefik
    
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # --- Configuração Simplificada para Depuração de SSL ---
        - "traefik.enable=true"
        - "traefik.docker.network=network_public" # IMPORTANTE: Use o nome da sua rede Traefik

        # --- Roteador HTTPS (Apenas para o domínio principal) ---
        - "traefik.http.routers.nextengine-app.rule=Host(`nextengine.com.br`)"
        - "traefik.http.routers.nextengine-app.entrypoints=websecure"
        - "traefik.http.routers.nextengine-app.tls=true"
        - "traefik.http.routers.nextengine-app.tls.certresolver=letsencrypt" # IMPORTANTE: Use o nome do seu resolver
        
        # --- Configuração do Serviço ---
        - "traefik.http.services.nextengine-app.loadbalancer.server.port=80"

# Declara a rede como externa, pois ela já foi criada pelo Traefik
networks:
  network_public: # IMPORTANTE: Verifique se este é o nome correto da sua rede Traefik
    external: true
