version: '3.8'

services:
  nextengine-app:
    # A imagem deve ser construída localmente antes do deploy com o nome "nextengine:latest"
    image: nextengine:latest
    networks:
      # Conecta o serviço à rede externa do Traefik
      - public_network # IMPORTANTE: Substitua 'web' pelo nome da sua rede Traefik
    
    # A chave 'deploy' é específica para o modo Swarm
    deploy:
      replicas: 1 # Define quantas instâncias do container devem rodar
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # --- Configuração do Traefik para Swarm ---
        # Habilita o Traefik para este serviço
        - "traefik.enable=true"
        
        # Especifica a rede Docker que o Traefik deve usar para se conectar a este serviço
        - "traefik.docker.network=network_public" # IMPORTANTE: Substitua 'web' pelo nome da sua rede Traefik

        # Define a regra de roteamento baseada no domínio
        - "traefik.http.routers.nextengine-app.rule=Host(`nextengine.com.br`)" # IMPORTANTE: Substitua pelo seu domínio
        
        # Define o ponto de entrada (geralmente 'websecure' para HTTPS)
        - "traefik.http.routers.nextengine-app.entrypoints=websecure"
        
        # Habilita o TLS (SSL) e especifica o resolvedor de certificados (ex: 'letsencrypt')
        - "traefik.http.routers.nextengine-app.tls=true"
        - "traefik.http.routers.nextengine-app.tls.certresolver=letsencrypt" # IMPORTANTE: Substitua pelo nome do seu resolver
        
        # Informa ao Traefik qual porta o container está usando internamente
        - "traefik.http.services.nextengine-app.loadbalancer.server.port=80"

# Declara a rede como externa, pois ela já foi criada pelo Traefik
networks:
  network_public: # IMPORTANTE: Substitua 'web' pelo nome da sua rede Traefik
    external: true
